### ISSUE TITLE
1.8.0 release does not contain zips for win32 platform

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio-sqlite#22]
The latest release 1.8.0 does not contain zips for win32 platform. I tried diffing the 1.8 and 1.7 release and could not find any obvious causes for the missing zips. 

Error: 
Smoke tests when running on windows platform tries to download the zip from the release which does not exists.
```
*** Downloading test extensions
  1) "before all" hook in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: the string "https://github.com/Microsoft/azuredatastudio-sqlite/releases/download/1.7.0/azuredatastudio-sqlite-win32-electron-13.6.6.zip: Not Found" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Release 1.8.0:
![image](https://user-images.githubusercontent.com/6816294/164945685-ff0020c4-9024-4396-863c-aec64abc22b9.png)

Release 1.7.0:
![image](https://user-images.githubusercontent.com/6816294/164945668-f9f90735-d8d2-4a36-84df-07a52cab3ef0.png)

This blocks smoke testing on windows platforms. 

@Charles-Gagnon and @kburtram

**Comment by aasimkhan30** [comment]
Found the Failed CD build for the release. It seems the windows build failed due to no valid visual studio installation.  https://github.com/microsoft/azuredatastudio-sqlite/runs/5842246100?check_suite_focus=true#step:4:54

**Comment by Charles-Gagnon** [comment]
Fixed https://github.com/microsoft/azuredatastudio-sqlite/pull/23
