### ISSUE TITLE
It's not working at all - Hanging Connection

### ISSUE THREAD

**Issue by ferox** [microsoft/azuredatastudio-sqlite#5]
Version: 1.27.0
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:15:38.801Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.11.10-300.fc34.x86_64 (Fedora Linux 34)

VSIX extension: azuredatastudio-sqlite-linux-node-12.14.1.vsix

The extension is successfully installed, but I can not open the database with the extension .db

![looping-after-button-connect-isshooted](https://user-images.githubusercontent.com/7634766/113485876-48a16f80-9486-11eb-87dd-bbfe250407d0.png)

**Comment by Charles-Gagnon** [comment]
Apologies @ferox - this package is only meant for testing purposes used by Azure Data Studio smoke tests. It is not intended to support SQLite connections outside of that at this time. I've updated the README to make this more clear.

**Comment by ferox** [comment]
Ok. Closing the issue.

**Comment by MesumRaza** [comment]
Please enable the plugin
